### ISSUE TITLE
Error importing

### ISSUE THREAD

**Issue by brucebailey** [JasPanesar/MuraConverter#14]
Have you guys encountered this error before?

javax.imageio.IIOException: Can't get input stream from URL!
Message     An exception occurred while trying to read the image.
StackTrace  coldfusion.image.ImageReader$ImageReadingException: An exception occurred while trying to read the image. at coldfusion.image.ImageReader.readImage(ImageReader.java:64) at coldfusion.image.Image.<init>(Image.java:233) at coldfusion.tagext.io.ImageTag.doStartTag(ImageTag.java:430) at cfwordpress2ecfc285351905$funcIMPORTIMAGES.runFunction(/opt/coldfusion9/wwwroot/junkyard/plugins/MuraConverter/admin/controllers/wordpress.cfc:276) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472) at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47) at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220) at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2582) at cfwordpress2ecfc285351905$funcCLEANWPPOST.runFunction(/opt/coldfusion9/wwwroot/junkyard/plugins/MuraConverter/admin/controllers/wordpress.cfc:207) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220) at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2582) at cfwordpress2ecfc285351905$funcIMPORT.runFunction(/opt/coldfusion9/wwwroot/junkyard/plugins/MuraConverter/admin/controllers/wordpress.cfc:80) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472) at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47) at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:517) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:495) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:354) at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2301) at coldfusion.tagext.lang.InvokeTag.doEndTag(InvokeTag.java:382) at cffw12ecfc924670$funcDOCONTROLLER.runFunction(/opt/coldfusion9/wwwroot/junkyard/plugins/MuraConverter/fw1.cfc:1248) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472) at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220) at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2582) at cffw12ecfc924670$funcONREQUEST.runFunction(/opt/coldfusion9/wwwroot/junkyard/plugins/MuraConverter/fw1.cfc:483) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:490) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:336) at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:88) at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:280) at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:338) at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:48) at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40) at coldfusion.filter.PathFilter.invoke(PathFilter.java:87) at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:70) at coldfusion.filter.BrowserDebugFilter.invoke(BrowserDebugFilter.java:74) at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28) at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38) at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:46) at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38) at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22) at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:53) at coldfusion.filter.RequestThrottleFilter.invoke(RequestThrottleFilter.java:126) at coldfusion.CfmServlet.service(CfmServlet.java:200) at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89) at jrun.servlet.FilterChain.doFilter(FilterChain.java:86) at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42) at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46) at jrun.servlet.FilterChain.doFilter(FilterChain.java:94) at jrun.servlet.FilterChain.service(FilterChain.java:101) at jrun.servlet.ServletInvoker.invoke(ServletInvoker.java:106) at jrun.servlet.JRunInvokerChain.invokeNext(JRunInvokerChain.java:42) at jrun.servlet.JRunRequestDispatcher.invoke(JRunRequestDispatcher.java:286) at jrun.servlet.ServletEngineService.dispatch(ServletEngineService.java:543) at jrun.servlet.jrpp.JRunProxyService.invokeRunnable(JRunProxyService.java:203) at jrunx.scheduler.ThreadPool$DownstreamMetrics.invokeRunnable(ThreadPool.java:320) at jrunx.scheduler.ThreadPool$ThreadThrottle.invokeRunnable(ThreadPool.java:428) at jrunx.scheduler.ThreadPool$UpstreamMetrics.invokeRunnable(ThreadPool.java:266) at jrunx.scheduler.WorkerThread.run(WorkerThread.java:66)

**Comment by gregmoser** [comment]
I have not seen that error before, but it also looks like you might be using an older version of the converter because that line number the error is being thrown from doesn't match up with anything that I can see in the code.

Have you updated to the latest?

-Greg

**Comment by brucebailey** [comment]
I had just installed the new version... it says I am on version .3

**Comment by JasPanesar** [comment]
This is a strange one.  The error appears to be coming from when the script tries to download the images in your Wordpress posts into Mura, and then link it into the Mura post itself.  I would check the URLs in the Wordpress post to the image to make sure they are not relative paths.  The script as far as I remember requires absolute paths to your images at the moment.

**Comment by brucebailey** [comment]
Just getting back to this as the boss is pushing hard for it.  I checked the source of the WP blog and it appears that they paths to the images are absolute.  Is there anything else I can check on?

**Comment by gregmoser** [comment]
I would try rapping that bit of code in a try/catch and see if some of them come across.  Then double check the specific path of any one(s) that fail.

**Comment by JasPanesar** [comment]
I can have a peek at this in the next few days and would start debugging this similarly to what Greg said.

If you can post the values above that you're able to extract, it might shine a bit more light on things.

**Comment by JasPanesar** [comment]
Some other things to check out:

http://stackoverflow.com/questions/10292792/getting-image-from-url-java

1) Are you behind a firewall?
2) Your url might have a space in it.  If we can see the url you're submitting I can have a look.
